export type Icons = 
| 'heart-outline'
| 'heart'

| 'chevron-forward-outline'
| 'chevron-back-outline'

| 'person-circle-outline'
| 'notifications-outline'
| 'cloud-upload-outline'
| 'alert-circle-outline'
| 'ellipsis-horizontal'
| 'chatbox-ellipses'
| 'location-outline'
| 'search-outline'
| 'remove-outline'
| 'create-outline'
| 'home-outline'
| 'cart-outline'
| 'add-outline'
| 'cog-outline'
| 'thumbs-up'
| 'star'

| 'phone-portrait'
| 'logo-playstation'
| 'laptop'
| 'camera'
| 'headset'
| 'fast-food'